desc "build Reticulator"
task :build_reticulator do
  %x(open Reticulator.mxi)
end

desc "build Reticulator (English)"
task :build_reticulator_en do
  %x(open Reticulator-en.mxi)
end

task :default => [:build_reticulator]